version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: styled-components
    versions:
    - 5.2.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
